//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticleAPIv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class art_user
    {
        public art_user()
        {
            this.menus = new HashSet<menu>();
            this.pages = new HashSet<page>();
        }
    
        public short user_id { get; set; }
        public string user_name { get; set; }
        public string email { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string gender { get; set; }
        public string passwd { get; set; }
    
        public virtual ICollection<menu> menus { get; set; }
        public virtual ICollection<page> pages { get; set; }
    }
}
