//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticleAPIv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public menu()
        {
            this.menu1 = new HashSet<menu>();
        }
    
        public short menu_id { get; set; }
        public string menu_title { get; set; }
        public Nullable<short> parent_id { get; set; }
        public short user_id { get; set; }
        public short page_id { get; set; }
    
        public virtual art_user art_user { get; set; }
        public virtual page page { get; set; }
        public virtual ICollection<menu> menu1 { get; set; }
        public virtual menu menu2 { get; set; }
    }
}
