//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticleAPIv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class page
    {
        public page()
        {
            this.menus = new HashSet<menu>();
        }
    
        public short page_id { get; set; }
        public string page_url { get; set; }
        public string page_title { get; set; }
        public string page_content { get; set; }
        public short user_id { get; set; }
        public System.DateTime created_date { get; set; }
    
        public virtual art_user art_user { get; set; }
        public virtual ICollection<menu> menus { get; set; }
    }
}
