//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticleAPIv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public short post_id { get; set; }
        public string post_title { get; set; }
        public string post_text { get; set; }
        public string post_image { get; set; }
        public System.DateTime post_date { get; set; }
        public string author { get; set; }
        public short category_id { get; set; }
    
        public virtual category category { get; set; }
    }
}
